FROM rabbitmq

# RUN update-rc.d rabbitmq-server defaults
# RUN /etc/init.d/rabbitmq-server start
# RUN rabbitmqctl add_vhost /sensu
# RUN rabbitmqctl add_user sensu secret
# RUN rabbitmqctl set_permissions -p /sensu sensu ".*" ".*" ".*"